# Amazon Web Scraping

In [2]:
from bs4 import BeautifulSoup
import requests
import smtplib
import time 
import datetime

In [3]:
URL = 'https://www.amazon.in/Amazon-Brand-Symbol-T-Shirt-AW17PLSR3_L_Pure/dp/B073X4KMH6/ref=sr_1_1_sspa?crid=DH4N24SMOXBF&dib=eyJ2IjoiMSJ9.HDKCzWonQZvEp2tbaQA26W8B-aoEDKA2F_LgHhZBakJ4k6333c5mOE2ylPb_RqBHtxrTqR6ObNCvPc3OZHAQK0qcXg6rbJzNDwCPEC-XtICS6gwXLY8p027QPXrROKU-6OC_Jm17peCbeOJKRWD8ThW52A_Kf4eQDfCqRtjM3WLL4Gzp4DcyabC1xD6TCoKAeJU0LJXQHmIi1V-wLDBXw_X99Poavf8hXI6Cu6ehQRMe_NRVI10n97CQMv5aRswD_ADI1-_td_R7xIaUGVt5OLxwUfsVlcDdGO68RVv1Lnk.sjhhbbo0IH7GprpVfCqw-F4sHqokjMexyWPYamOJ3NY&dib_tag=se&keywords=t+shirt+for+man&qid=1792335018&sprefix=t%2Caps%2C274&sr=8-1-spons&aref=vIZa9tF2bn&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1'

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/155.0.0.0 Safari/537.36"}

page = requests.get(URL, headers = headers)

soup1 = BeautifulSoup(page.content, 'html.parser')

soup2 = BeautifulSoup(soup1.prettify(), 'html.parser')

title = soup2.find(id = 'productTitle').get_text()

price = soup2.find(class_ = 'a-price-whole').get_text()


print(title)
print(price)

                 Amazon Brand - Symbol Men's Solid Cotton T Shirt | Round Neck | Half Sleeve | Plain-Regular Fit (Available in Plus Sizes)


                    249

In [4]:
price = price.strip()
title = title.strip()

print(title)
print(price)

Amazon Brand - Symbol Men's Solid Cotton T Shirt | Round Neck | Half Sleeve | Plain-Regular Fit (Available in Plus Sizes)
249

In [9]:
import datetime 

today = datetime.date.today()

In [10]:
import csv 

header = ['Title', 'Price', 'Date']
data = [title, price, today]

with open('AmazonWebScraperDataset.csv', 'w', newline = '', encoding = 'UTF8') as f:
    writer = csv.writer(f)
    writer.writerow(header)
    writer.writerow(data)

In [16]:
import pandas as pd 

df = pd.read_csv(r"D:\OMKAR\Python\Projects\AmazonWebScraperDataset.csv")

df

                                               Title  Price        Date
0  Amazon Brand - Symbol Men's Solid Cotton T Shi...    249  2026-10-19
1  Amazon Brand - Symbol Men's Solid Cotton T Shi...    249  2026-10-19
2  Amazon Brand - Symbol Men's Solid Cotton T Shi...    249  2026-10-19
3  Amazon Brand - Symbol Men's Solid Cotton T Shi...    249  2026-10-19

In [15]:
with open('AmazonWebScraperDataset.csv', 'a+', newline = '', encoding = 'UTF8') as f:
    writer = csv.writer(f)
    writer.writerow(data)

In [17]:
def check_price():
    URL = 'https://www.amazon.in/Amazon-Brand-Symbol-T-Shirt-AW17PLSR3_L_Pure/dp/B073X4KMH6/ref=sr_1_1_sspa?crid=DH4N24SMOXBF&dib=eyJ2IjoiMSJ9.HDKCzWonQZvEp2tbaQA26W8B-aoEDKA2F_LgHhZBakJ4k6333c5mOE2ylPb_RqBHtxrTqR6ObNCvPc3OZHAQK0qcXg6rbJzNDwCPEC-XtICS6gwXLY8p027QPXrROKU-6OC_Jm17peCbeOJKRWD8ThW52A_Kf4eQDfCqRtjM3WLL4Gzp4DcyabC1xD6TCoKAeJU0LJXQHmIi1V-wLDBXw_X99Poavf8hXI6Cu6ehQRMe_NRVI10n97CQMv5aRswD_ADI1-_td_R7xIaUGVt5OLxwUfsVlcDdGO68RVv1Lnk.sjhhbbo0IH7GprpVfCqw-F4sHqokjMexyWPYamOJ3NY&dib_tag=se&keywords=t+shirt+for+man&qid=1792335018&sprefix=t%2Caps%2C274&sr=8-1-spons&aref=vIZa9tF2bn&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1'

    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/155.0.0.0 Safari/537.36"}

    page = requests.get(URL, headers = headers)

    soup1 = BeautifulSoup(page.content, 'html.parser')

    soup2 = BeautifulSoup(soup1.prettify(), 'html.parser')

    title = soup2.find(id = 'productTitle').get_text()

    price = soup2.find(class_ = 'a-price-whole').get_text()

    price = price.strip()
    title = title.strip()

    import datetime 

    today = datetime.date.today()

    import csv 

    header = ['Title', 'Price', 'Date']
    data = [title, price, today]

    with open('AmazonWebScraperDataset.csv', 'a+', newline = '', encoding = 'UTF8') as f:
        writer = csv.writer(f)
        writer.writerow(data)

    if(price < 200):
        send_mail()

In [ ]:
while(True):
    check_price()
    time.sleep(86400)

In [19]:
import pandas as pd 

df = pd.read_csv(r"D:\OMKAR\Python\Projects\AmazonWebScraperDataset.csv")

df

                                               Title  Price        Date
0  Amazon Brand - Symbol Men's Solid Cotton T Shi...    249  2026-10-19
1  Amazon Brand - Symbol Men's Solid Cotton T Shi...    249  2026-10-19
2  Amazon Brand - Symbol Men's Solid Cotton T Shi...    249  2026-10-19
3  Amazon Brand - Symbol Men's Solid Cotton T Shi...    249  2026-10-19
4  Amazon Brand - Symbol Men's Solid Cotton T Shi...    249  2026-10-19

In [ ]:
def send_mail():
    server = smtplib.SMTP_SSL('smtp.gmail.com',465)
    server.ehlo()
    #server.starttls()
    server.ehlo()
    server.login('pawarom2108@gmail.com','xxxxxxxxxxxxxx')
    
    subject = "The Shirt you want is below Rs 200! Now is your chance to buy!"
    body = "Alex, This is the moment we have been waiting for. Now is your chance to pick up the shirt of your dreams. Don't mess it up! Link here: https://www.amazon.com/Funny-Data-Systems-Business-Analyst/dp/B07FNW9FGJ/ref=sr_1_3?dchild=1&keywords=data+analyst+tshirt&qid=1626655184&sr=8-3"
   
    msg = f"Subject: {subject}\n\n{body}"
    
    server.sendmail(
        'pawarom2108@gmail.com',
        msg
     
    )