# Automating Crupto Website API

In [76]:

from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json

url = 'https://api.coingecko.com/api/v3/coins/markets'

Parameters = {
    'vs_currency': 'usd',
    'order': 'market_cap_desc',
    'per_page': '20',
    'page': '1',
    'sparkline': 'false'
}

headers = {
    'accept': 'application/json',
    'x-cg-demo-api-key': 'CG-A1vUD3P41ZQt6WP5nJKa5Y6s'
}

session = Session()
session.headers.update(headers)

try:
    response = session.get(
        url,
        params=Parameters,
        timeout=(10, 60)
    )
    response.raise_for_status()
    data = json.loads(response.text)

except (ConnectionError, Timeout, TooManyRedirects) as e:
    print(e)

In [77]:
type(data)

list

In [78]:
import pandas as pd

In [102]:
pd.set_option('display.max.columns', None)
pd.set_option('display.max.rows', None)

In [86]:
df = pd.json_normalize(data)
df['timestamp'] = pd.to_datetime('now')
df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,low_24h,price_change_24h,price_change_percentage_24h,market_cap_change_24h,market_cap_change_percentage_24h,circulating_supply,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated,roi.times,roi.currency,roi.percentage,timestamp
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,81380.000000,1635580485222,1,1635580485222,24861235468,83015.000000,81155.000000,-1313.451725,-1.58834,-2.646019e+10,-1.59203,2.009884e+07,2.009884e+07,2.100000e+07,126080.000000,-35.45370,2025-10-06T10:57:42.000Z,67.810000,1.199134e+05,2013-07-05T16:00:00.000Z,NaN,2026-10-20T08:16:48.000Z,NaN,NaN,NaN,2026-10-20 13:53:14.280393
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2383.720000,291180463193,2,291180463193,9307746606,2443.800000,2374.520000,-45.826288,-1.88621,-5.584289e+09,-1.88172,1.221513e+08,1.221513e+08,NaN,4946.050000,-51.80560,2025-08-24T11:21:03.000Z,0.432979,5.504392e+05,2015-10-19T16:00:00.000Z,NaN,2026-10-20T08:16:48.000Z,43.309090,btc,4330.908963,2026-10-20 13:53:14.280393
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999229,183027506862,3,188490016946,46222535550,0.999436,0.999131,-0.000129,-0.01288,-5.195207e+08,-0.28304,1.831762e+11,1.886432e+11,NaN,1.320000,-24.47794,2018-07-23T16:00:00.000Z,0.572521,7.453138e+01,2015-03-01T16:00:00.000Z,NaN,2026-10-20T08:16:48.000Z,NaN,NaN,NaN,2026-10-20 13:53:14.280393
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,728.070000,95752986210,4,95752986210,673036325,732.900000,722.800000,3.110000,0.42857,-7.819727e+08,-0.81004,1.315120e+08,1.315120e+08,2.000000e+08,1369.990000,-46.85581,2025-10-13T00:41:24.000Z,0.039818,1.828411e+06,2017-10-18T16:00:00.000Z,NaN,2026-10-20T08:16:48.000Z,NaN,NaN,NaN,2026-10-20 13:53:14.280393
4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.290000,81730023797,5,129445092369,1262972633,1.320000,1.290000,-0.017802,-1.35627,-1.133006e+09,-1.36732,6.312967e+10,9.998561e+10,1.000000e+11,3.650000,-64.49127,2025-07-17T19:40:53.000Z,0.002686,4.810115e+04,2014-05-21T16:00:00.000Z,NaN,2026-10-20T08:16:48.000Z,NaN,NaN,NaN,2026-10-20 13:53:14.280393
5,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,0.999936,72110953568,6,72148470541,16206819208,1.000000,0.999321,0.000064,0.00641,-3.094132e+08,-0.42725,7.211833e+10,7.215585e+10,NaN,1.043000,-4.17153,2018-11-14T16:00:00.000Z,0.877647,1.393380e+01,2023-03-11T00:02:13.000Z,NaN,2026-10-20T08:16:48.000Z,NaN,NaN,NaN,2026-10-20 13:53:14.280393
6,solana,sol,Solana,https://coin-images.coingecko.com/coins/images...,104.060000,61328958960,7,66176718396,2418125785,105.870000,103.540000,-1.593388,-1.50815,-9.460293e+08,-1.51912,5.894932e+08,6.360898e+08,NaN,293.310000,-64.52300,2025-01-19T03:15:27.000Z,0.500801,2.067836e+04,2020-05-11T11:35:23.000Z,NaN,2026-10-20T08:16:48.000Z,NaN,NaN,NaN,2026-10-20 13:53:14.280393
7,tron,trx,TRON,https://coin-images.coingecko.com/coins/images...,0.331750,31516873879,8,31517306098,301502507,0.332272,0.330529,0.000917,0.27709,8.684946e+07,0.27633,9.500391e+10,9.500521e+10,NaN,0.431288,-23.07935,2024-12-03T16:10:40.000Z,0.001804,1.828620e+04,2017-11-11T16:00:00.000Z,NaN,2026-10-20T08:16:48.000Z,175.853881,usd,17585.388090,2026-10-20 13:53:14.280393
8,figure-heloc,figr_heloc,Figure Heloc,https://coin-images.coingecko.com/coins/images...,1.021000,24521447853,9,24521447853,19253529,1.053000,1.017000,NaN,NaN,NaN,NaN,2.401802e+10,2.401802e+10,NaN,1.075000,-5.05605,2026-10-05T13:59:20.000Z,0.155357,5.571437e+02,2025-10-31T06:27:24.000Z,NaN,2026-10-20T08:16:48.000Z,NaN,NaN,NaN,2026-10-20 13:53:14.280393
9,zcash,zec,Zcash,https://coin-images.coingecko.com/coins/images...,1129.110000,19188604859,10,19188961209,637683589,1172.470000,1110.620000,-32.884363,-2.83000,-5.545961e+08,-2.80905,1.699568e+07,1.699600e+07,2.100000e+07,3191.930000,-64.62621,2016-10-28T16:00:00.000Z,16.080000,6.921750e+03,2024-07-04T20:22:29.000Z,NaN,2026-10-20T08:16:48.000Z,NaN,NaN,NaN,2026-10-20 13:53:14.280393
10,hyperliquid,hype,Hyperliquid,https://coin-images.coingecko.com/coins/images...,78.450000,17453084289,11,74953365807,507525597,80.130000,77.570000,-1.411314,-1.76729,-3.108597e+08,-1.74995,2.224457e+08,9.553071e+08,1.000000e+09,97.960000,-19.92261,2026-09-23T05:16:50.000Z,3.810000,1.959635e+03,2024-11-29T01:30:30.000Z,NaN,2026-10-20T08:16:48.000Z,NaN,NaN,NaN,2026-10-20 13:53:14.280393
11,dogecoin,doge,Dogecoin,https://coin-images.coingecko.com/coins/images...,0.079017,12355759687,12,12355946133,354101004,0.079960,0.078486,-0.000588,-0.73859,-9.277084e+07,-0.74524,1.563969e+11,1.563993e+11,NaN,0.731578,-89.19913,2021-05-07T21:08:23.000Z,0.000087,9.082449e+04,2015-05-05T16:00:00.000Z,NaN,2026-10-20T08:16:48.000Z,NaN,NaN,NaN,2026-10-20 13:53:14.280393
12,monero,xmr,Monero,https://coin-images.coingecko.com/coins/images...,613.400000,11543228844,13,11543228844,178247000,612.520000,583.670000,18.350000,3.08406,3.447385e+08,3.07844,1.881998e+07,1.881998e+07,NaN,797.730000,-23.10763,2026-01-14T11:34:07.000Z,0.216177,2.836481e+05,2015-01-13T16:00:00.000Z,NaN,2026-10-20T08:16:48.000Z,NaN,NaN,NaN,2026-10-20 13:53:14.280393
13,usds,usds,USDS,https://coin-images.coingecko.com/coins/images...,1.000000,10048262121,14,10048262121,98501233,1.002000,0.999910,0.000151,0.01507,-1.603797e+08,-1.57102,1.004583e+10,1.004583e+10,NaN,1.057000,-5.39454,2024-10-28T21:40:51.000Z,0.948265,5.485740e+00,2024-10-03T05:19:28.000Z,NaN,2026-10-20T08:16:48.000Z,NaN,NaN,NaN,2026-10-20 13:53:14.280393
14,whitebit,wbt,WhiteBIT Coin,https://coin-images.coingecko.com/coins/images...,79.520000,9442401584,15,23319006848,95124898,81.140000,79.300000,-1.283830,-1.58886,-1.557739e+08,-1.62295,1.187866e+08,2.933561e+08,4.000000e+08,87.910000,-9.54948,2026-09-21T20:29:10.000Z,3.060000,2.497188e+03,2023-02-13T11:01:21.000Z,NaN,2026-10-20T08:16:48.000Z,NaN,NaN,NaN,2026-10-20 13:53:14.280393
15,chainlink,link,Chainlink,https://coin-images.coingecko.com/coins/images...,11.920000,9141085602,16,11920305086,222913074,12.180000,11.840000,-0.255309,-2.09702,-1.951724e+08,-2.09048,7.668500e+08,1.000000e+09,1.000000e+09,52.700000,-77.38079,2021-05-09T16:13:57.000Z,0.148183,7.943797e+03,2017-11-28T16:00:00.000Z,NaN,2026-10-20T08:16:48.000Z,NaN,NaN,NaN,2026-10-20 13:53:14.280393
16,leo-token,leo,LEO Token,https://coin-images.coingecko.com/coins/images...,9.040000,8312345984,17,8903170873,144818,9.040000,9.010000,0.001845,0.02042,1.942740e+06,0.02338,9.198579e+08,9.852395e+08,NaN,10.610000,-14.85806,2026-05-04T09:35:00.000Z,0.799859,1.029735e+03,2019-12-24T07:14:35.000Z,NaN,2026-10-20T08:16:48.000Z,NaN,NaN,NaN,2026-10-20 13:53:14.280393
17,cardano,ada,Cardano,https://coin-images.coingecko.com/coins/images...,0.216077,8114232023,18,9721673062,217688977,0.221014,0.214856,-0.004277,-1.94096,-1.621545e+08,-1.95924,3.755942e+10,4.500000e+10,4.500000e+10,3.090000,-93.00020,2021-09-01T22:00:10.000Z,0.019253,1.022320e+03,2020-03-12T18:22:55.000Z,NaN,2026-10-20T08:16:48.000Z,NaN,NaN,NaN,2026-10-20 13:53:14.280393
18,stellar,xlm,Stellar,https://coin-images.coingecko.com/coins/images...,0.176584,6221422941,19,8835393554,103733843,0.178632,0.175040,-0.002017,-1.12923,-6.564070e+07,-1.04406,3.520865e+10,5.000179e+10,NaN,0.875563,-79.83189,2018-01-02T16:00:00.000Z,0.000476,3.698796e+04,2015-03-04T16:00:00.000Z,NaN,2026-10-20T08:16:48.000Z,NaN,NaN,NaN,2026-10-20 13:53:14.280393
19,near,near,NEAR Protocol,https://coin-images.coingecko.com/coins/images...,4.750000,6214899264,20,6214899255,666882955,5.090000,4.750000,-0.298704,-5.92204,-3.893624e+08,-5.89562,1.309428e+09,1.309428e+09,NaN,20.440000,-76.78248,2022-01-16T14:09:45.000Z,0.526762,8.008281e+02,2020-11-04T08:09:15.000Z,NaN,2026-10-20T08:16:48.000Z,NaN,NaN,NaN,2026-10-20 13:53:14.280393

In [118]:
df = pd.DataFrame()
def api_runner():
    global df
    url = 'https://api.coingecko.com/api/v3/coins/markets'
    
    Parameters = {
        'vs_currency': 'usd',
        'order': 'market_cap_desc',
        'per_page': '20',
        'page': '1',
        'sparkline': 'false'
    }
    
    headers = {
        'accept': 'application/json',
        'x-cg-demo-api-key': 'CG-A1vUD3P41ZQt6WP5nJKa5Y6s'
    }
    
    session = Session()
    session.headers.update(headers)
    
    try:
        response = session.get(
            url,
            params=Parameters,
            timeout=(10, 60)
        )
        response.raise_for_status()
        data = json.loads(response.text)
    
    except (ConnectionError, Timeout, TooManyRedirects) as e:
        print(e)

    df = pd.json_normalize(data)
    df['timestamp'] = pd.to_datetime('now')

    if not os.path.isfile(r'D:/OMKAR/Python/Crypto automation Project/API.csv'):
        df.to_csv(r'D:/OMKAR/Python/Crypto automation Project/API.csv', header='column_names', index=False)
    else:
        df.to_csv(r'D:/OMKAR/Python/Crypto automation Project/API.csv', mode='a', header=False, index=False)

In [119]:
import os
from time import time
from time import sleep

for i in range(333):
    api_runner()
    print("api runner completed")
    sleep(6)
exit()

api runner completed
api runner completed
api runner completed
api runner completed

KeyboardInterrupt:

In [120]:
df27 = pd.read_csv(r'D:/OMKAR/Python/Crypto automation Project/API.csv')
df27

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,low_24h,price_change_24h,price_change_percentage_24h,market_cap_change_24h,market_cap_change_percentage_24h,circulating_supply,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated,roi.times,roi.currency,roi.percentage,timestamp
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,81352.000000,1635101815106,1,1635101815106,24869617096,82807.000000,81155.000000,-1349.362718,-1.63161,-2.710062e+10,-1.63040,2.009884e+07,2.009884e+07,2.100000e+07,126080.000000,-35.47580,2025-10-06T10:57:42.000Z,67.810000,1.198723e+05,2013-07-05T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:43.445304
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2378.680000,290558610380,2,290558610380,9367360824,2436.650000,2374.520000,-54.391632,-2.23551,-6.637659e+09,-2.23343,1.221513e+08,1.221513e+08,NaN,4946.050000,-51.90735,2025-08-24T11:21:03.000Z,0.432979,5.492769e+05,2015-10-19T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,43.309090,btc,4330.908963,2026-10-20 14:40:43.445304
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999100,183015330664,3,188477477346,46233736919,0.999436,0.999095,-0.000216,-0.02162,-5.241185e+08,-0.28556,1.831762e+11,1.886432e+11,NaN,1.320000,-24.48766,2018-07-23T16:00:00.000Z,0.572521,7.450892e+01,2015-03-01T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:43.445304
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,726.690000,95569205576,4,95569205576,662319709,732.900000,722.800000,1.150000,0.15858,-1.042033e+09,-1.07858,1.315120e+08,1.315120e+08,2.000000e+08,1369.990000,-46.95681,2025-10-13T00:41:24.000Z,0.039818,1.824936e+06,2017-10-18T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:43.445304
4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.290000,81531468214,5,129130617412,1273949666,1.310000,1.290000,-0.020634,-1.57252,-1.303967e+09,-1.57417,6.312967e+10,9.998561e+10,1.000000e+11,3.650000,-64.58092,2025-07-17T19:40:53.000Z,0.002686,4.797946e+04,2014-05-21T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:43.445304
5,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,0.999845,72097378697,6,72102956998,16218097149,1.000000,0.999321,-0.000003,-0.00031,-3.027851e+08,-0.41821,7.210903e+10,7.211461e+10,NaN,1.043000,-4.18029,2018-11-14T16:00:00.000Z,0.877647,1.392338e+01,2023-03-11T00:02:13.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:43.445304
6,solana,sol,Solana,https://coin-images.coingecko.com/coins/images...,103.890000,61240250095,7,66080997468,2421492057,105.520000,103.540000,-1.549419,-1.46950,-9.091569e+08,-1.46286,5.894931e+08,6.360897e+08,NaN,293.310000,-64.58065,2025-01-19T03:15:27.000Z,0.500801,2.064460e+04,2020-05-11T11:35:23.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:43.445304
7,tron,trx,TRON,https://coin-images.coingecko.com/coins/images...,0.331991,31543663072,8,31544121317,300130038,0.332272,0.330602,0.001246,0.37684,1.220074e+08,0.38829,9.500391e+10,9.500529e+10,NaN,0.431288,-23.02333,2024-12-03T16:10:40.000Z,0.001804,1.829959e+04,2017-11-11T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,175.853881,usd,17585.388090,2026-10-20 14:40:43.445304
8,figure-heloc,figr_heloc,Figure Heloc,https://coin-images.coingecko.com/coins/images...,1.021000,24523007061,9,24523007061,19255483,1.053000,1.017000,NaN,NaN,NaN,NaN,2.401802e+10,2.401802e+10,NaN,1.075000,-5.04642,2026-10-05T13:59:20.000Z,0.155357,5.572104e+02,2025-10-31T06:27:24.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:43.445304
9,zcash,zec,Zcash,https://coin-images.coingecko.com/coins/images...,1127.590000,19162190411,10,19162687204,633869415,1167.470000,1110.620000,-37.511208,-3.21957,-6.338545e+08,-3.20193,1.699568e+07,1.699612e+07,2.100000e+07,3191.930000,-64.67372,2016-10-28T16:00:00.000Z,16.080000,6.912318e+03,2024-07-04T20:22:29.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:43.445304
10,hyperliquid,hype,Hyperliquid,https://coin-images.coingecko.com/coins/images...,78.400000,17440362342,11,74898730607,517199137,79.920000,77.570000,-1.445529,-1.81042,-3.208489e+08,-1.80646,2.224457e+08,9.553071e+08,1.000000e+09,97.960000,-19.97008,2026-09-23T05:16:50.000Z,3.810000,1.958414e+03,2024-11-29T01:30:30.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:43.445304
11,dogecoin,doge,Dogecoin,https://coin-images.coingecko.com/coins/images...,0.078815,12325786327,12,12326046403,362177859,0.079957,0.078486,-0.000850,-1.06658,-1.320763e+08,-1.06018,1.563969e+11,1.564002e+11,NaN,0.731578,-89.22675,2021-05-07T21:08:23.000Z,0.000087,9.059199e+04,2015-05-05T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:43.445304
12,monero,xmr,Monero,https://coin-images.coingecko.com/coins/images...,612.150000,11518113199,13,11518113199,179231351,616.480000,583.670000,22.630000,3.83784,4.234405e+08,3.81661,1.882000e+07,1.882000e+07,NaN,797.730000,-23.26344,2026-01-14T11:34:07.000Z,0.216177,2.830731e+05,2015-01-13T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:43.445304
13,usds,usds,USDS,https://coin-images.coingecko.com/coins/images...,1.000000,10047706746,14,10047706746,87681482,1.002000,0.999910,0.000221,0.02206,-1.422690e+08,-1.39617,1.004589e+10,1.004589e+10,NaN,1.057000,-5.39465,2024-10-28T21:40:51.000Z,0.948265,5.485620e+00,2024-10-03T05:19:28.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:43.445304
14,whitebit,wbt,WhiteBIT Coin,https://coin-images.coingecko.com/coins/images...,79.450000,9438578501,15,23309565341,96293353,80.950000,79.300000,-1.397535,-1.72859,-1.651120e+08,-1.71926,1.187866e+08,2.933561e+08,4.000000e+08,87.910000,-9.62600,2026-09-21T20:29:10.000Z,3.060000,2.494990e+03,2023-02-13T11:01:21.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:43.445304
15,chainlink,link,Chainlink,https://coin-images.coingecko.com/coins/images...,11.890000,9118514870,16,11890872037,223452282,12.150000,11.840000,-0.264492,-2.17591,-2.029023e+08,-2.17673,7.668500e+08,1.000000e+09,1.000000e+09,52.700000,-77.43494,2021-05-09T16:13:57.000Z,0.148183,7.924540e+03,2017-11-28T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:43.445304
16,leo-token,leo,LEO Token,https://coin-images.coingecko.com/coins/images...,9.010000,8291301034,17,8880630090,21243,9.040000,9.010000,-0.020092,-0.22241,-1.852670e+07,-0.22295,9.198579e+08,9.852395e+08,NaN,10.610000,-15.07064,2026-05-04T09:35:00.000Z,0.799859,1.026914e+03,2019-12-24T07:14:35.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:43.445304
17,cardano,ada,Cardano,https://coin-images.coingecko.com/coins/images...,0.215150,8080360512,18,9681091556,218380661,0.220329,0.214856,-0.005195,-2.35760,-1.956803e+08,-2.36442,3.755942e+10,4.500000e+10,4.500000e+10,3.090000,-93.03024,2021-09-01T22:00:10.000Z,0.019253,1.017505e+03,2020-03-12T18:22:55.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:43.445304
18,stellar,xlm,Stellar,https://coin-images.coingecko.com/coins/images...,0.175621,6182156569,19,8779629255,108169588,0.178185,0.175040,-0.002573,-1.44379,-9.055651e+07,-1.44366,3.520865e+10,5.000179e+10,NaN,0.875563,-79.94195,2018-01-02T16:00:00.000Z,0.000476,3.678558e+04,2015-03-04T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:43.445304
19,near,near,NEAR Protocol,https://coin-images.coingecko.com/coins/images...,4.710000,6173388886,20,6173388976,667765107,5.060000,4.710000,-0.343914,-6.79881,-4.498828e+08,-6.79246,1.309455e+09,1.309455e+09,NaN,20.440000,-76.93265,2022-01-16T14:09:45.000Z,0.526762,7.950015e+02,2020-11-04T08:09:15.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:43.445304
20,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,81352.000000,1635101815106,1,1635101815106,24869617096,82807.000000,81155.000000,-1349.362718,-1.63161,-2.710062e+10,-1.63040,2.009884e+07,2.009884e+07,2.100000e+07,126080.000000,-35.47580,2025-10-06T10:57:42.000Z,67.810000,1.198723e+05,2013-07-05T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:49.753760
21,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2378.680000,290558610380,2,290558610380,9367360824,2436.650000,2374.520000,-54.391632,-2.23551,-6.637659e+09,-2.23343,1.221513e+08,1.221513e+08,NaN,4946.050000,-51.90735,2025-08-24T11:21:03.000Z,0.432979,5.492769e+05,2015-10-19T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,43.309090,btc,4330.908963,2026-10-20 14:40:49.753760
22,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999100,183015330664,3,188477477346,46233736919,0.999436,0.999095,-0.000216,-0.02162,-5.241185e+08,-0.28556,1.831762e+11,1.886432e+11,NaN,1.320000,-24.48766,2018-07-23T16:00:00.000Z,0.572521,7.450892e+01,2015-03-01T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:49.753760
23,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,726.690000,95569205576,4,95569205576,662319709,732.900000,722.800000,1.150000,0.15858,-1.042033e+09,-1.07858,1.315120e+08,1.315120e+08,2.000000e+08,1369.990000,-46.95681,2025-10-13T00:41:24.000Z,0.039818,1.824936e+06,2017-10-18T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:49.753760
24,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.290000,81531468214,5,129130617412,1273949666,1.310000,1.290000,-0.020634,-1.57252,-1.303967e+09,-1.57417,6.312967e+10,9.998561e+10,1.000000e+11,3.650000,-64.58092,2025-07-17T19:40:53.000Z,0.002686,4.797946e+04,2014-05-21T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:49.753760
25,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,0.999845,72097378697,6,72102956998,16218097149,1.000000,0.999321,-0.000003,-0.00031,-3.027851e+08,-0.41821,7.210903e+10,7.211461e+10,NaN,1.043000,-4.18029,2018-11-14T16:00:00.000Z,0.877647,1.392338e+01,2023-03-11T00:02:13.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:49.753760
26,solana,sol,Solana,https://coin-images.coingecko.com/coins/images...,103.890000,61240250095,7,66080997468,2421492057,105.520000,103.540000,-1.549419,-1.46950,-9.091569e+08,-1.46286,5.894931e+08,6.360897e+08,NaN,293.310000,-64.58065,2025-01-19T03:15:27.000Z,0.500801,2.064460e+04,2020-05-11T11:35:23.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:49.753760
27,tron,trx,TRON,https://coin-images.coingecko.com/coins/images...,0.331991,31543663072,8,31544121317,300130038,0.332272,0.330602,0.001246,0.37684,1.220074e+08,0.38829,9.500391e+10,9.500529e+10,NaN,0.431288,-23.02333,2024-12-03T16:10:40.000Z,0.001804,1.829959e+04,2017-11-11T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,175.853881,usd,17585.388090,2026-10-20 14:40:49.753760
28,figure-heloc,figr_heloc,Figure Heloc,https://coin-images.coingecko.com/coins/images...,1.021000,24523007061,9,24523007061,19255483,1.053000,1.017000,NaN,NaN,NaN,NaN,2.401802e+10,2.401802e+10,NaN,1.075000,-5.04642,2026-10-05T13:59:20.000Z,0.155357,5.572104e+02,2025-10-31T06:27:24.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:49.753760
29,zcash,zec,Zcash,https://coin-images.coingecko.com/coins/images...,1127.590000,19162190411,10,19162687204,633869415,1167.470000,1110.620000,-37.511208,-3.21957,-6.338545e+08,-3.20193,1.699568e+07,1.699612e+07,2.100000e+07,3191.930000,-64.67372,2016-10-28T16:00:00.000Z,16.080000,6.912318e+03,2024-07-04T20:22:29.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:49.753760
30,hyperliquid,hype,Hyperliquid,https://coin-images.coingecko.com/coins/images...,78.400000,17440362342,11,74898730607,517199137,79.920000,77.570000,-1.445529,-1.81042,-3.208489e+08,-1.80646,2.224457e+08,9.553071e+08,1.000000e+09,97.960000,-19.97008,2026-09-23T05:16:50.000Z,3.810000,1.958414e+03,2024-11-29T01:30:30.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:49.753760
31,dogecoin,doge,Dogecoin,https://coin-images.coingecko.com/coins/images...,0.078815,12325786327,12,12326046403,362177859,0.079957,0.078486,-0.000850,-1.06658,-1.320763e+08,-1.06018,1.563969e+11,1.564002e+11,NaN,0.731578,-89.22675,2021-05-07T21:08:23.000Z,0.000087,9.059199e+04,2015-05-05T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:49.753760
32,monero,xmr,Monero,https://coin-images.coingecko.com/coins/images...,612.150000,11518113199,13,11518113199,179231351,616.480000,583.670000,22.630000,3.83784,4.234405e+08,3.81661,1.882000e+07,1.882000e+07,NaN,797.730000,-23.26344,2026-01-14T11:34:07.000Z,0.216177,2.830731e+05,2015-01-13T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:49.753760
33,usds,usds,USDS,https://coin-images.coingecko.com/coins/images...,1.000000,10047706746,14,10047706746,87681482,1.002000,0.999910,0.000221,0.02206,-1.422690e+08,-1.39617,1.004589e+10,1.004589e+10,NaN,1.057000,-5.39465,2024-10-28T21:40:51.000Z,0.948265,5.485620e+00,2024-10-03T05:19:28.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:49.753760
34,whitebit,wbt,WhiteBIT Coin,https://coin-images.coingecko.com/coins/images...,79.450000,9438578501,15,23309565341,96293353,80.950000,79.300000,-1.397535,-1.72859,-1.651120e+08,-1.71926,1.187866e+08,2.933561e+08,4.000000e+08,87.910000,-9.62600,2026-09-21T20:29:10.000Z,3.060000,2.494990e+03,2023-02-13T11:01:21.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:49.753760
35,chainlink,link,Chainlink,https://coin-images.coingecko.com/coins/images...,11.890000,9118514870,16,11890872037,223452282,12.150000,11.840000,-0.264492,-2.17591,-2.029023e+08,-2.17673,7.668500e+08,1.000000e+09,1.000000e+09,52.700000,-77.43494,2021-05-09T16:13:57.000Z,0.148183,7.924540e+03,2017-11-28T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:49.753760
36,leo-token,leo,LEO Token,https://coin-images.coingecko.com/coins/images...,9.010000,8291301034,17,8880630090,21243,9.040000,9.010000,-0.020092,-0.22241,-1.852670e+07,-0.22295,9.198579e+08,9.852395e+08,NaN,10.610000,-15.07064,2026-05-04T09:35:00.000Z,0.799859,1.026914e+03,2019-12-24T07:14:35.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:49.753760
37,cardano,ada,Cardano,https://coin-images.coingecko.com/coins/images...,0.215150,8080360512,18,9681091556,218380661,0.220329,0.214856,-0.005195,-2.35760,-1.956803e+08,-2.36442,3.755942e+10,4.500000e+10,4.500000e+10,3.090000,-93.03024,2021-09-01T22:00:10.000Z,0.019253,1.017505e+03,2020-03-12T18:22:55.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:49.753760
38,stellar,xlm,Stellar,https://coin-images.coingecko.com/coins/images...,0.175621,6182156569,19,8779629255,108169588,0.178185,0.175040,-0.002573,-1.44379,-9.055651e+07,-1.44366,3.520865e+10,5.000179e+10,NaN,0.875563,-79.94195,2018-01-02T16:00:00.000Z,0.000476,3.678558e+04,2015-03-04T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:49.753760
39,near,near,NEAR Protocol,https://coin-images.coingecko.com/coins/images...,4.710000,6173388886,20,6173388976,667765107,5.060000,4.710000,-0.343914,-6.79881,-4.498828e+08,-6.79246,1.309455e+09,1.309455e+09,NaN,20.440000,-76.93265,2022-01-16T14:09:45.000Z,0.526762,7.950015e+02,2020-11-04T08:09:15.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:49.753760
40,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,81352.000000,1635101815106,1,1635101815106,24869617096,82807.000000,81155.000000,-1349.362718,-1.63161,-2.710062e+10,-1.63040,2.009884e+07,2.009884e+07,2.100000e+07,126080.000000,-35.47580,2025-10-06T10:57:42.000Z,67.810000,1.198723e+05,2013-07-05T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:56.063940
41,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2378.680000,290558610380,2,290558610380,9367360824,2436.650000,2374.520000,-54.391632,-2.23551,-6.637659e+09,-2.23343,1.221513e+08,1.221513e+08,NaN,4946.050000,-51.90735,2025-08-24T11:21:03.000Z,0.432979,5.492769e+05,2015-10-19T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,43.309090,btc,4330.908963,2026-10-20 14:40:56.063940
42,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999100,183015330664,3,188477477346,46233736919,0.999436,0.999095,-0.000216,-0.02162,-5.241185e+08,-0.28556,1.831762e+11,1.886432e+11,NaN,1.320000,-24.48766,2018-07-23T16:00:00.000Z,0.572521,7.450892e+01,2015-03-01T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:56.063940
43,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,726.690000,95569205576,4,95569205576,662319709,732.900000,722.800000,1.150000,0.15858,-1.042033e+09,-1.07858,1.315120e+08,1.315120e+08,2.000000e+08,1369.990000,-46.95681,2025-10-13T00:41:24.000Z,0.039818,1.824936e+06,2017-10-18T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:56.063940
44,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.290000,81531468214,5,129130617412,1273949666,1.310000,1.290000,-0.020634,-1.57252,-1.303967e+09,-1.57417,6.312967e+10,9.998561e+10,1.000000e+11,3.650000,-64.58092,2025-07-17T19:40:53.000Z,0.002686,4.797946e+04,2014-05-21T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:56.063940
45,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,0.999845,72097378697,6,72102956998,16218097149,1.000000,0.999321,-0.000003,-0.00031,-3.027851e+08,-0.41821,7.210903e+10,7.211461e+10,NaN,1.043000,-4.18029,2018-11-14T16:00:00.000Z,0.877647,1.392338e+01,2023-03-11T00:02:13.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:56.063940
46,solana,sol,Solana,https://coin-images.coingecko.com/coins/images...,103.890000,61240250095,7,66080997468,2421492057,105.520000,103.540000,-1.549419,-1.46950,-9.091569e+08,-1.46286,5.894931e+08,6.360897e+08,NaN,293.310000,-64.58065,2025-01-19T03:15:27.000Z,0.500801,2.064460e+04,2020-05-11T11:35:23.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:56.063940
47,tron,trx,TRON,https://coin-images.coingecko.com/coins/images...,0.331991,31543663072,8,31544121317,300130038,0.332272,0.330602,0.001246,0.37684,1.220074e+08,0.38829,9.500391e+10,9.500529e+10,NaN,0.431288,-23.02333,2024-12-03T16:10:40.000Z,0.001804,1.829959e+04,2017-11-11T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,175.853881,usd,17585.388090,2026-10-20 14:40:56.063940
48,figure-heloc,figr_heloc,Figure Heloc,https://coin-images.coingecko.com/coins/images...,1.021000,24523007061,9,24523007061,19255483,1.053000,1.017000,NaN,NaN,NaN,NaN,2.401802e+10,2.401802e+10,NaN,1.075000,-5.04642,2026-10-05T13:59:20.000Z,0.155357,5.572104e+02,2025-10-31T06:27:24.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:56.063940
49,zcash,zec,Zcash,https://coin-images.coingecko.com/coins/images...,1127.590000,19162190411,10,19162687204,633869415,1167.470000,1110.620000,-37.511208,-3.21957,-6.338545e+08,-3.20193,1.699568e+07,1.699612e+07,2.100000e+07,3191.930000,-64.67372,2016-10-28T16:00:00.000Z,16.080000,6.912318e+03,2024-07-04T20:22:29.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:56.063940
50,hyperliquid,hype,Hyperliquid,https://coin-images.coingecko.com/coins/images...,78.400000,17440362342,11,74898730607,517199137,79.920000,77.570000,-1.445529,-1.81042,-3.208489e+08,-1.80646,2.224457e+08,9.553071e+08,1.000000e+09,97.960000,-19.97008,2026-09-23T05:16:50.000Z,3.810000,1.958414e+03,2024-11-29T01:30:30.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:56.063940
51,dogecoin,doge,Dogecoin,https://coin-images.coingecko.com/coins/images...,0.078815,12325786327,12,12326046403,362177859,0.079957,0.078486,-0.000850,-1.06658,-1.320763e+08,-1.06018,1.563969e+11,1.564002e+11,NaN,0.731578,-89.22675,2021-05-07T21:08:23.000Z,0.000087,9.059199e+04,2015-05-05T16:00:00.000Z,NaN,2026-10-20T09:09:46.000Z,NaN,NaN,NaN,2026-10-20 14:40:56.063940