# Group By and Aggregate

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"D:\OMKAR\Python\Pandas_Learning\Raw Data\Flavors.csv")
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [24]:
group_by_frame = df.groupby('Base Flavor')

In [32]:
group_by_frame.mean(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [37]:
df.groupby('Base Flavor').mean(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [39]:
df.groupby('Base Flavor').count()

             Flavor  Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate         3      3              3               3             3
Vanilla           6      6              6               6             6

In [40]:
df.groupby('Base Flavor').min()

                  Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate      Chocolate   Yes            8.2             7.0          15.2
Vanilla      Cake Batter    No            2.3             3.4           5.7

In [41]:
df.groupby('Base Flavor').max()

                 Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate    Rocky Road   Yes            8.8             7.6          16.6
Vanilla         Vanilla   Yes           10.0             8.0          18.0

In [43]:
df.groupby('Base Flavor').sum(numeric_only = True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate             25.2            21.7          47.1
Vanilla               34.2            33.9          68.1

In [44]:
df.groupby('Base Flavor').agg({'Flavor Rating': ['mean', 'count', 'max', 'min', 'sum']})

            Flavor Rating
                     mean count   max  min   sum
Base Flavor
Chocolate             8.4     3   8.8  8.2  25.2
Vanilla               5.7     6  10.0  2.3  34.2

In [45]:
df.groupby('Base Flavor').agg({'Flavor Rating': ['mean', 'count', 'max', 'min', 'sum'], 'Texture Rating': ['mean', 'count', 'max', 'min', 'sum']})

            Flavor Rating                        Texture Rating             \
                     mean count   max  min   sum           mean count  max
Base Flavor
Chocolate             8.4     3   8.8  8.2  25.2       7.233333     3  7.6
Vanilla               5.7     6  10.0  2.3  34.2       5.650000     6  8.0


             min   sum
Base Flavor
Chocolate    7.0  21.7
Vanilla      3.4  33.9

In [49]:
df.groupby(['Base Flavor', 'Liked']).sum(numeric_only = True)

                   Flavor Rating  Texture Rating  Total Rating
Base Flavor Liked
Chocolate   Yes             25.2            21.7          47.1
Vanilla     No              10.8            13.4          24.2
            Yes             23.4            20.5          43.9

In [50]:
df.groupby(['Base Flavor', 'Liked']).agg({'Flavor Rating': ['mean', 'count', 'max', 'min', 'sum']})

                  Flavor Rating
                           mean count   max  min   sum
Base Flavor Liked
Chocolate   Yes             8.4     3   8.8  8.2  25.2
Vanilla     No              3.6     3   4.7  2.3  10.8
            Yes             7.8     3  10.0  6.5  23.4

In [53]:
df.groupby('Base Flavor').describe()

            Flavor Rating                                             \
                    count mean       std  min    25%  50%  75%   max
Base Flavor
Chocolate             3.0  8.4  0.346410  8.2  8.200  8.2  8.5   8.8
Vanilla               6.0  5.7  2.710719  2.3  4.025  5.6  6.8  10.0

            Texture Rating                                                  \
                     count      mean       std  min   25%  50%    75%  max
Base Flavor
Chocolate              3.0  7.233333  0.321455  7.0  7.05  7.1  7.350  7.6
Vanilla                6.0  5.650000  1.566844  3.4  5.00  5.5  6.375  8.0

            Total Rating
                   count   mean       std   min     25%   50%     75%   max
Base Flavor
Chocolate            3.0  15.70  0.781025  15.2  15.250  15.3  15.950  16.6
Vanilla              6.0  11.35  4.263684   5.7   9.025  11.1  13.175  18.0

In [55]:
# pd.set_option('display.max.columns', 40)